name: CASMLCV
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - pytorch-lightning
  - scikit-learn
  - scikit-image
  - imagecodecs
  - numpy
  - matplotlib
  - napari
  - pandas
  - seaborn
  - pip
  - jupyterlab=3.*
  - ipywidgets
  - pip:
    - albumentations
    - captum
    - tqdm
    - opencv-python
    - psutil